version: '3'
services:
  ghost_db:
    hostname: ghost_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    networks:
      - backghost

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    depends_on:
      - ghost_db

    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: ghost_db
      database__connection__host: db
      database__connection__user: root
      database__connection__password: $MYSQL_PASSWORD
      database__connection__database: ghost
      url: http://localhost:8080

    labels:
      - traefik.enable=true
      - traefik.docker.network=frontend
      - traefik.http.routers.ghost.tls.certresolver=myresolver
      - traefik.http.routers.ghost.rule=Host(`$DOMAIN`)
      - traefik.http.services.ghost.loadbalancer.server.port=8005

    # command: "sleep 5d"
    command: "poetry run bash launch.sh"
    networks:
      - frontend
      - backghost


      
networks:
  frontend:
    external: true
  backghost:
